version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install --force
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Uploading to S3...
      - aws s3 sync ./dist/ s3://frontend-exam-tuxona/ --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E1T7BFAJDAOE9B --paths "/*"
artifacts:
  files:
    - '**/*'

